
package uk.co.o2.soa.chargecustomerservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ChargeCustomerService", targetNamespace = "http://soa.o2.co.uk/chargecustomerservice_1", wsdlLocation = "file:/D:/tmp/o2/chargecustomerservice_1_0.xml")
public class ChargeCustomerService
    extends Service
{

    private final static URL CHARGECUSTOMERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(uk.co.o2.soa.chargecustomerservice.ChargeCustomerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = uk.co.o2.soa.chargecustomerservice.ChargeCustomerService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/tmp/o2/chargecustomerservice_1_0.xml");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/tmp/o2/chargecustomerservice_1_0.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CHARGECUSTOMERSERVICE_WSDL_LOCATION = url;
    }

    public ChargeCustomerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChargeCustomerService() {
        super(CHARGECUSTOMERSERVICE_WSDL_LOCATION, new QName("http://soa.o2.co.uk/chargecustomerservice_1", "ChargeCustomerService"));
    }

    /**
     * 
     * @return
     *     returns ChargeCustomerPort
     */
    @WebEndpoint(name = "ChargeCustomerPort")
    public ChargeCustomerPort getChargeCustomerPort() {
        return super.getPort(new QName("http://soa.o2.co.uk/chargecustomerservice_1", "ChargeCustomerPort"), ChargeCustomerPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChargeCustomerPort
     */
    @WebEndpoint(name = "ChargeCustomerPort")
    public ChargeCustomerPort getChargeCustomerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.o2.co.uk/chargecustomerservice_1", "ChargeCustomerPort"), ChargeCustomerPort.class, features);
    }

}
