
package uk.co.o2.soa.subscriberservice_2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SubscriberService", targetNamespace = "http://soa.o2.co.uk/subscriberservice_2", wsdlLocation = "file:/C:/TEMP/O2%20Integration/WelcomePack/WelcomePack/SOAServices/subscriberservice_2_0.wsdl")
public class SubscriberService
    extends Service
{

    private final static URL SUBSCRIBERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(uk.co.o2.soa.subscriberservice_2.SubscriberService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = uk.co.o2.soa.subscriberservice_2.SubscriberService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/TEMP/O2%20Integration/WelcomePack/WelcomePack/SOAServices/subscriberservice_2_0.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/TEMP/O2%20Integration/WelcomePack/WelcomePack/SOAServices/subscriberservice_2_0.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SUBSCRIBERSERVICE_WSDL_LOCATION = url;
    }

    public SubscriberService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriberService() {
        super(SUBSCRIBERSERVICE_WSDL_LOCATION, new QName("http://soa.o2.co.uk/subscriberservice_2", "SubscriberService"));
    }

    /**
     * 
     * @return
     *     returns SubscriberPort
     */
    @WebEndpoint(name = "SubscriberPort")
    public SubscriberPort getSubscriberPort() {
        return super.getPort(new QName("http://soa.o2.co.uk/subscriberservice_2", "SubscriberPort"), SubscriberPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriberPort
     */
    @WebEndpoint(name = "SubscriberPort")
    public SubscriberPort getSubscriberPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.o2.co.uk/subscriberservice_2", "SubscriberPort"), SubscriberPort.class, features);
    }

}
